echo 'Namenode:'
docker exec -it namenode /bin/bash -c 'jps'
echo 'SecNamenode:'
docker exec -it secnamenode /bin/bash -c 'jps'
echo 'resmgr:'
docker exec -it resmgr /bin/bash -c 'jps'
echo 'datanode1:'
docker exec -it datanode1 /bin/bash -c 'jps'
echo 'datanode2:'
docker exec -it datanode2 /bin/bash -c 'jps'
echo 'datanode2:'
docker exec -it datanode3 /bin/bash -c 'jps'